### ISSUE TITLE
Coverage fails with "Cannot find module" for .bin/c8

### ISSUE THREAD

**Issue by trivikr** [nodejs/quic#151]
* **Version**: v13.0.0-pre
* **Platform**: Ubuntu
* **Subsystem**: quic

Command run: `./configure --coverage && make -j4 coverage`

Output:
```console
Makefile:296: recipe for target 'jstest' failed
make[2]: *** [jstest] Error 1
Makefile:335: recipe for target 'test-cov' failed
make[1]: *** [test-cov] Error 2
Makefile:245: recipe for target 'coverage-test' failed
make: [coverage-test] Error 2 (ignored)
make coverage-report-js
./node ./node_modules/.bin/c8 report --reporter=html --temp-directory=out/Release/.coverage --omit-relative=false --resolve=./lib --exclude="benchmark/" --exclude="deps/" --exclude="test/" --exclude="tools/" --wrapper-length=0
internal/modules/cjs/loader.js:782
    throw err;
    ^

Error: Cannot find module '/home/trivikr/workspace/quic/node_modules/.bin/c8'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:779:15)
    at Function.Module._load (internal/modules/cjs/loader.js:684:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1015:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Makefile:273: recipe for target 'coverage-report-js' failed
make[1]: *** [coverage-report-js] Error 1
Makefile:245: recipe for target 'coverage-test' failed
make: *** [coverage-test] Error 2
```

![Screenshot from 2019-10-04 00-44-30](https://user-images.githubusercontent.com/16024985/66190363-af9b5980-e640-11e9-8fd7-7aa925ca7d93.png)

**Comment by trivikr** [comment]
This issue was fixed after I ran `make distclean` as discussed in https://github.com/nodejs/node/issues/28675

`make coverage` is now successful
