### ISSUE TITLE
Error tests coverage on macOS

### ISSUE THREAD

**Issue by juanarbol** [nodejs/quic#197]
* **Version**:  v13.0.0-pre
* **Platform**: macOS Mojave 10.14.6

First time I ran:
```sh
$ ./configure --experimental-quic --coverage
$ make -j4 coverage
```
It worked, but now it's not working on my machine (and already ran `make clean`), this is the log:
```
=== release test-source-map ===
Path: parallel/test-source-map
internal/modules/cjs/loader.js:980
    throw err;
    ^

SyntaxError: /Users/juanjose/Documents/GitHub/Node/quic/out/Release/.coverage/coverage-11591-1573853622685-0.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:977:27)
    at Module.load (internal/modules/cjs/loader.js:797:32)
    at Function.Module._load (internal/modules/cjs/loader.js:710:12)
    at Module.require (internal/modules/cjs/loader.js:837:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at getSourceMapFromCache (/Users/juanjose/Documents/GitHub/Node/quic/test/parallel/test-source-map.js:122:33)
    at Object.<anonymous> (/Users/juanjose/Documents/GitHub/Node/quic/test/parallel/test-source-map.js:32:21)
    at Module._compile (internal/modules/cjs/loader.js:946:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:963:10)
Command: out/Release/node /Users/juanjose/Documents/GitHub/Node/quic/test/parallel/test-source-map.js
=== release test-worker-message-port-transfer-terminate ===
Path: parallel/test-worker-message-port-transfer-terminate
Command: out/Release/node /Users/juanjose/Documents/GitHub/Node/quic/test/parallel/test-worker-message-port-transfer-terminate.js
--- CRASHED (Signal: 6) ---
=== release test-inspector-contexts ===
Path: sequential/test-inspector-contexts
Testing context created/destroyed notifications
Command: out/Release/node --expose-gc /Users/juanjose/Documents/GitHub/Node/quic/test/sequential/test-inspector-contexts.js
--- TIMEOUT ---
[17:03|% 100|+ 2797|-   4]: Done
make[2]: *** [jstest] Error 1
make[1]: *** [test-cov] Error 2
make: [coverage-test] Error 2 (ignored)
/Applications/Xcode.app/Contents/Developer/usr/bin/make coverage-report-js
./node ./node_modules/.bin/c8 report --reporter=html --temp-directory=out/Release/.coverage --omit-relative=false --resolve=./lib --exclude="benchmark/" --exclude="deps/" --exclude="test/" --exclude="tools/" --wrapper-length=0
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/report.js:174:21
    at Array.map (<anonymous>)
    at Report._loadReports (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/report.js:172:18)
    at Report._getMergedProcessCov (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/report.js:142:37)
    at Report.getCoverageMapFromAllCoverageFiles (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/report.js:59:31)
    at Report.run (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/report.js:39:28)
    at Object.exports.outputReport (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/commands/report.js:24:16)
    at Object.exports.handler (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/commands/report.js:9:17)
    at Object.runCommand (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/yargs/lib/command.js:237:40)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/report.js:174:21
    at Array.map (<anonymous>)
    at Report._loadReports (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/report.js:172:18)
    at Report._getMergedProcessCov (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/report.js:142:37)
    at Report.getCoverageMapFromAllCoverageFiles (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/report.js:59:31)
    at Report.run (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/report.js:39:28)
    at Object.exports.outputReport (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/commands/report.js:24:16)
    at Object.exports.handler (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/c8/lib/commands/report.js:9:17)
    at Object.runCommand (/Users/juanjose/Documents/GitHub/Node/quic/node_modules/yargs/lib/command.js:237:40)

<--- Last few GCs --->
lo[38626:0x105a46000]    33862 ms: Mark-sweep 2050.9 (2053.9) -> 2049.7 (2054.1) MB, 2123.4 / 0.0 ms  (+ 127.4 ms in 29 steps since start of marking, biggest step 9.0 ms, walltime since start of marking 2268 ms) (average mu = 0.112, current mu = 0.008) allo[38626:0x105a46000]    36145 ms: Mark-sweep 2050.0 (2054.1) -> 2049.5 (2053.1) MB, 2280.2 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2282 ms) (average mu = 0.058, current mu = 0.002) allocat

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x101a1a82d]
Security context: 0x2d391ef408a1 <JSObject>
    1: toString [0x2d39120b7f89] [buffer.js:~741] [pc=0x142c765e0d4e](this=0x2d39ca093131 <Uint8Array map = 0x2d39f0fe5d71>,0x2d39120a0441 <String[#4]: utf8>,0x2d39280404a9 <undefined>,0x2d39280404a9 <undefined>)
    2: arguments adaptor frame: 1->3
    3: /* anonymous */(aka /* anonymous */) [0x2d399ffa37d1] [/Users/juanjose/Documents/GitHub/Node/quic/node_mod...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10014cd0b node::DumpBacktrace(__sFILE*) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
 2: 0x1005d57a8 node::Abort() [/Users/juanjose/Documents/GitHub/Node/quic/./node]
 3: 0x1005d5b91 node::OnFatalError(char const*, char const*) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
 4: 0x1012b8387 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
 5: 0x1012b8327 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
 6: 0x10143fca5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
 7: 0x10144151a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
 8: 0x10143dfec v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
 9: 0x10143be0e v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
10: 0x101447c30 v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
11: 0x101447c7f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
12: 0x1014177c9 v8::internal::Factory::NewRawOneByteString(int, v8::internal::AllocationType) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
13: 0x1014178d6 v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const> const&, v8::internal::AllocationType) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
14: 0x1012da1a2 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
15: 0x100c1b4f1 node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
16: 0x100473db2 void node::Buffer::(anonymous namespace)::StringSlice<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/juanjose/Documents/GitHub/Node/quic/./node]
17: 0x101a1a82d Builtins_CallApiCallback [/Users/juanjose/Documents/GitHub/Node/quic/./node]
make[1]: *** [coverage-report-js] Abort trap: 6
make: *** [coverage-test] Error 2
```

I've no idea, I've built and cleaned up like 4 times. It's weird, because the binary is built but coverage stuff crashes.

**Comment by juanarbol** [comment]
Just delete and re-cloned the repo again :/

**Comment by juanarbol** [comment]
This issue persists, I just checkout to master, made a pull, and re run `make -j4 coverage`, same error.

**Comment by trivikr** [comment]
Coverage on macOS also fails upstream https://github.com/nodejs/node/issues/19057

**Comment by juanarbol** [comment]
Sorry, I do not knew about that issue. I'm closing it, this seems to be a duplicated issue.

**Comment by trivikr** [comment]
@juanarbol I've uploaded current coverage results at https://nodejs-quic-coverage.netlify.com/

**Comment by juanarbol** [comment]
Very nice! Is there a way to help with updating that content, so if another person runs the coverage script, could send a PR or something like that, that coverage could be more precise (something like nightly coverage on node core but not automated)

**Comment by trivikr** [comment]
I don't have permissions to add netlify GitHub app to nodejs/quic, so I did this instead:
* Used [pull app](https://github.com/apps/pull) to auto-sync trivikr/quic from nodejs/quic 
* Set up build on trivikr/quic when master branch is updated in netlify app.
* Selected domain name to be https://nodejs-quic-coverage.netlify.com/

The deployment failed though https://app.netlify.com/sites/nodejs-quic-coverage/deploys/5ddae8e492e2f8b2522842a5

**Comment by juanarbol** [comment]
I was thinking about something more manual, like a GitHub pages with coverage static files, If anyone ran coverage script, just commit and send a PR to the main repo (it's only a suggestion).
